name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}


      - name: Set short SHA
        run: echo "SHORT_SHA=$(echo $GITHUB_SHA | cut -c1-7)" >> $GITHUB_ENV

      - name: Build Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository_owner }}/webapi:${{ env.SHORT_SHA }} -t ghcr.io/${{ github.repository_owner }}/webapi:latest -f Dockerfile .

      - name: Push Docker image (version)
        run: docker push ghcr.io/${{ github.repository_owner }}/webapi:${{ env.SHORT_SHA }}

      - name: Push Docker image (latest)
        run: docker push ghcr.io/${{ github.repository_owner }}/webapi:latest


